# Generated by Django 2.0 on 2018-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='品牌机构', max_length=10, verbose_name='机构标签'),
        ),
    ]
